[build]
  command = "pnpm run build"
  publish = ".next"

# Disable secrets scanning since we're using demo Firebase credentials
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Alternative: Skip specific paths if you want scanning enabled but want to exclude build artifacts
# [build.environment]
#   SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"